### ISSUE TITLE
docker installation failed, because the name of the downloaded file is different

### ISSUE THREAD

**Issue by CREITZ25** [devonfw/ide#1006]
### Actual behavior

Filenames are: docker-stable-windows.exe and docker-stable-win.exe

$ devon docker setup

Trying to download **docker-stable-windows.exe** from 
...
Download of **docker-stable-windows.exe** from https:...

*** Installing Docker Desktop for Windows... ***

functions: line 84: /c/Users/creitz/Downloads/devonfw-ide/**docker-stable-win.exe**: No such file or directory

$ ls -alF /c/Users/creitz/Downloads/devonfw-ide/
total 599240
drwxr-xr-x 1 creitz 1049089         0 Dec 12 11:19 ./
drwxr-xr-x 1 creitz 1049089         0 Dec 12 11:17 ../
-rwxr-xr-x 1 creitz 1049089 613613904 Dec 12 11:19 **docker-stable-windows.exe**

**Comment by hohwille** [comment]
See here:
https://github.com/devonfw/ide/blob/478794db3388f7cd80e11f937facb7d03086eb38/scripts/src/main/resources/scripts/command/docker#L98

**Comment by cinnamon-coder-hub** [comment]
With PR #1037 the installation of Docker Desktop should be doable again. 
There was a hardcoded file name "docker-stable-win.exe", which was used for executing the file "docker-stable-windows.exe". 
My first guess is, that this had something to do with the os-variable in the functions file, 
used for generating the final name of the Docker Desktop executable and an approach change. 
So it would be nice to have a little team chat about this on monday, to make sure that the issue is now really solved, as @CREITZ25 and @hohwille  have deep knowledge here : )
