### ISSUE TITLE
SonarQube start and stop options do not work correct

### ISSUE THREAD

**Issue by CREITZ25** [devonfw/ide#1154]
As a user, I want start and stop SonarQube Server.

### Expected behavior

The command "devon sonar help" indicates that you can start the Sonarqube server in the background with the start option and stop it again with stop.

### Actual behavior

In practice, however, this is not the case. The command "devon sonar stop" calls a script that doesn't exist, and "devon sonar start" starts the server in the foreground.

### Steps to reproduce (bug)

$ devon sonar start
--> works in foreground
CTRL+c --> process ended

$ devon sonar stop
/c/Users/creitz/Projects/devonfw/scripts/command/sonar: line 45: /c/Users/creitz/Projects/devonfw/software/sonarqube/bin/windows-x86-64/StopNTService.bat: No such file or directory

**Comment by Oumal1** [comment]
the StoptNTService.bat File does not exist in all SonarQube Versions. the Last Version that includes this file is the Version 8.9. 
if you have the latest version the stop won't work because it's calling a file that does not exists in the Sonarqube folder.

The server can be stopped using the Ctrl+c  key combination. In this Case the Server Stops Properly and there is no need to run the stop command
- it Probably more useful to run Ctrl+c because not all the versions are running the same file to Stop the Server.

**Comment by Oumal1** [comment]
In Case the Stop command isn't working to stop the Sonarqube . the Following Command should be run
 %SONARQUBE_HOME%\bin\windows-x86-64\SonarService.bat install
afterwards the Server will stop successfully. for more Information take a look at the following Documentation
[https://docs.sonarqube.org/9.7/setup-and-upgrade/configure-and-operate-a-server/operating-the-server/](url)
