### ISSUE TITLE
Projects main-branch is always checked out

### ISSUE THREAD

**Issue by mduggen** [devonfw/ide#1158]
### Expected behavior

As a devonfw-ide admin I want to setup projects with other branches than main. 

### Actual behavior

The main branch is always checked out even if another branch has been set.

### Steps to reproduce (bug)

1. Setup a project by creating a project.properties file.
2. Set `git.branch` property to any branch except main.

### Comments/Hints:

Function called:
```
# $1: absolute target path
# $2: URL (may be URL#branch)
function doGitPullOrClone() {..}
```

Call from function doImportProject() in command/project with:
```
doGitPullOrClone "${project_path}" "${project_git_url}" "${project_git_branch}"
```

Seems that the last parameter 'project_git_branch' is ignored.

**Comment by hohwille** [comment]
@mduggen thanks for your detailed bug report. 👍 
OMG fully true (was this ever tested or did this ever work?):
https://github.com/devonfw/ide/blob/2d3797905e0f250cf3cfcd26f3d57052a96b12c9/scripts/src/main/resources/scripts/command/project#L87

but
https://github.com/devonfw/ide/blob/2d3797905e0f250cf3cfcd26f3d57052a96b12c9/scripts/src/main/resources/scripts/functions#L1151-L1153

Easy to fix though. As we are currently working on epic #941 I wont be able to push out a fix release quickly so it will need some weeks to get a fix released. You could try to test a SNAPSHOT once a fixing PR is merged though. However...

Simple workaround:
In your project `*.properties` file add `#«your-branch»` to the end of your `git.url`.

**Comment by hohwille** [comment]
> You could try to test a SNAPSHOT once a fixing PR is merged though. However...
fixing PR is merged. In max 1h it will be available: https://github.com/devonfw/ide/blob/master/documentation/setup.asciidoc#testing-snapshot-releases

You can also open the PR (linked under `Development` in the side-bar) and go to `files changed` then you see the diff. As all is mainly just bash scripts, you can apply this change to your own installation if you want.
Once `2023.05.001` is released, users can simply enter `devon ide update scripts` and the bug is gone.
