### ISSUE TITLE
Rancher Desktop download file changes from exe to msi

### ISSUE THREAD

**Issue by CREITZ25** [devonfw/ide#1200]
For the Rancher Desktop releases, the software packages for Windows were provided either as exe or msi files. So far we have always used the exe version. Since Release 1.9.0 only the msi version is provided and as of Release 1.9.0 the file windows_x64.urls is missing in the IDE-URLs.

We should switch to the msi versions and it must be noted that the msi files do not have to be unpacked but installed.

**Comment by hohwille** [comment]
So as can been seen from the associated commits, I deleted the 1.9.0 release folder and changed the updater to use msi instead of exe. Tonight the job will recreate the 1.9.0 folder with windows url included pointing to MSI. All earlier versions use exe and still work. This is the benefit of our new approach that could not be solved with mirrors before (versions until at least 1.0.0 did not have msi but only exe and versions 1.9.0 and newer only have msi).
