### ISSUE TITLE
Is mvn installation on Windows broken?

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/ide#268]
### Expected behavior

As a user I want to install Maven on Windows so that I can use it for Java development or for the CobiGen CLI

### Actual behavior

Testing Beta22 I'm not able to run `devon mvn setup` without getting an error when extracting:

```Bash
Starting installation of maven to C:\Users\jdiazgon\Desktop\temp\devon-ide\my-project\devon-ide-scripts-3.0.0-beta22.tar/software/maven from http://ftp.fau.de/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
Artifact already exists at /c/Users/jdiazgon/Downloads/maven-3.6.1.tar.gz
To force update please delete the file and run again.
Running command: tar xf '/c/Users/jdiazgon/Downloads/maven-3.6.1.tar.gz' -C 'C:\Users\jdiazgon\Desktop  emp\devon-ide\my-project\devon-ide-scripts-3.0.0-beta22.tar/updates/extracted/maven'
tar: C\:\\Users\\jdiazgon\\Desktop\temp\\devon-ide\\my-project\\devon-ide-scripts-3.0.0-beta22.tar/updates/extracted/maven: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

******** ATTENTION ********
ERROR: Failed to run command tar
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 2
```
If I go to `C\:\\Users\\jdiazgon\\Desktop\temp\\devon-ide\\my-project\\devon-ide-scripts-3.0.0-beta22.tar/updates/extracted/maven` I can see that the `maven` folder is there.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. In Windows download [Beta22](https://repo.maven.apache.org/maven2/com/devonfw/tools/ide/devon-ide-scripts/3.0.0-beta22/).
2. Run `setup`.
3. Run `devon`.
4. Run `devon mvn setup`.
5. You will have the errors mentioned above.

### Comments/Hints:

I get that error on a clean copy.

### Affected version:

* OS: Windows
* Browser: Chrome

**Comment by markusschuh** [comment]
Can you see, which `bash` is executed on your system? If you don't know, please report the output of `git --version` and `where git` here.

I use the recent [2.23.0](https://git-scm.com/download/win)  The `devon-ide` currently has some other issues, which best where resolved before too much other testing ( see #262 ) But even, if not, the output of pathname in Windows notation  `C:\...` is unexpected here and might be the cause of this issue.

In my case the output is instead:

```
Artifact already exists at /c/Users/user/Downloads/maven-3.6.1.tar.gz
To force update please delete the file and run again.
Running command: tar xf '/c/Users/user/Downloads/maven-3.6.1.tar.gz' -C '/c/opt/devon-ide-scripts-3.0.0-beta22/updates/extracted/maven'
Succeeded to run command tar
```

I get this already during run of the initial `setup` - but it is the same, if I later remove the `software\maven` sub folder and run `devon mvn setup` again.

**Comment by jdiazgon** [comment]
Thanks for your answer @markusschuh . So it's my fault because I didn't read properly the documentation. I was using Windows CMD rather than Git bash.

I have installed the latest Git bash version (`2.23.0`) and I have tried to run some simple commands like `devon java` or `devon mvn`. I'm not able to run any of those because they throw `unknown command`:
![image](https://user-images.githubusercontent.com/31688036/66188550-cb761e00-e687-11e9-840e-3502a19a6472.png)

I have executed the `setup.bat` as explained on the Wiki. The output of `echo ${PATH}` is:

```BASH
/c/Users/jdiazgon/Desktop/temp/software/*
/c/Users/jdiazgon/bin
/mingw64/bin
/usr/local/bin
/usr/bin
/bin
/mingw64/bin
/usr/bin
/c/Users/jdiazgon/bin
/c/Program Files/Docker/Docker/Resources/bin
/c/ProgramData/Oracle/Java/javapath
/c/WINDOWS/system32
/c/WINDOWS
/c/WINDOWS/System32/Wbem
/c/WINDOWS/System32/WindowsPowerShell/v1.0
/c/Program Files/TortoiseGit/bin
/c/Program Files (x86)/apache-maven-3.5.4/apache-maven/src/bin
/c/Program Files/Java/jdk1.8.0_181
/c/apache-maven-3.5.4/bin
/c/Program Files/nodejs
/c/Program Files/Microsoft VS Code/bin
/c/ProgramData/chocolatey/bin
/c/Program Files/MiKTeX 2.9/miktex/bin/x64
/c/Program Files (x86)/GnuPG/bin
/c/Users/jdiazgon/Desktop/CobiGen/software/graal/mx
/c/Program Files/Intel/WiFi/bin
/c/Program Files/Common Files/Intel/WirelessCommon
/c/WINDOWS/System32/OpenSSH
/cmd
/c/Users/jdiazgon/AppData/Local/Programs/Python/Python37/Scripts
/c/Users/jdiazgon/AppData/Local/Programs/Python/Python37
/c/Users/jdiazgon/AppData/Local/Microsoft/WindowsApps
/c/Users/jdiazgon/AppData/Roaming/npm
/c/Users/jdiazgon/AppData/Local/Programs/Fiddler
/c/Users/jdiazgon/AppData/Local/Microsoft/WindowsApps
/usr/bin/vendor_perl
/usr/bin/core_perl
```
Can you give me any hints on this? When I was using the Windows CMD it was correctly executing all the commands but `devon mvn setup`. I don't get why with Git bash it is not working.

**Comment by markusschuh** [comment]
The first entry in your list (with the `*`at the end) is completely unexpected and not helpful. I have no idea, from where that could originate. Nevertheless this alone can't be the reason for your remaining issues. 

I need to "dive" deeper:  The so far realized logic of this devon-ide is the following:

You **can** start `setup.bat` from within a Windows-CMD. (That is, what happens, when you double click it in explorer) The "setup.bat"  calls "devon.bat" and this

1. tries to locate a `bash.exe` from git-for-windows installation and uses this
1. if not found tries to locate a `bash.exe` from cygwin installation and uses this
1. if also not found, outputs the below text (added at end of my posting ) and stops.

In your case - when you initially has opened this issue - it looks a bit as if another logic was used. You haven't reported the original output of the first commands -but at least the path name in Windows notation in the first line of output from `devon mvn setup` was unexpected. It would be helpful to understand, what has happend here under the hood. At the moment I have two different theses:

- If you had an older devon-ide on this system it could be - even when this already was removed again - the original `setup` still sees the old  `%USERPROFILE%\scripts\devon.bat`   and /or 
 `%USERPROFILE%\.devon\devon`  and does not overwrite it with a newer version. If this older component was used, the script logic might have been different.
- Also I can imagine some unexpected cases, where als a `bash` from `%SystemRoot%\system32\bash.exe" might have been called. From the path components you have listed, you seem to use Windows 10. If that has `WSL` activated, the bash would exist. `WSL` is an option for be supported by devon-ide, too - but this needs far more effort. Especially since `WSL` itself is still quite "agile" in its own development. 

Please check, if any existing `/c/Users/jdiazgon/bin/scripts/devon.bat` is the same as the devon.bat in your target folder of the extracted tar.gz   Do the same for any `/c/Users/jdiazgon/bin/.devon/devon` (this is bash script, while the first is a CMD script)
If there is some difference, that might explain the errors , when you execute e.g. `devon java`.  Also try first `devon help`.  This should also help you to understand, that `devon setup`  is no existing sub command.

If all this does not help, you need to narrow down, what commands in what directories are really called, when you run your commands. I have suggested a enhancement to increase debug level by setting an environment variable before call within #261 - but this isn't realized inside devon-ide yet.

And a hint: Keep the target path shorter. Your extraction in .../Desktop/temp/....tar/... isn't formally wrong and I don't expect, this causes on its own problems. But this makes analyze of output far harder to read ;-)

PS: For the sake of completeness, here is the error message, that should be displayed, if neither Git-for-Windows nor cygwin is identified as installed on the system. Which might be caused also due to incomplete detection.

```
*** ATTENTION ***
Bash has not been found on your system!
Please install git for windows on your system.
https://git-scm.com/download/win
```
goto :eof

**Comment by jdiazgon** [comment]
Thanks a lot @markusschuh! Your first thesis was right. I installed the `devon-ide` a long time ago and there were some old files:

![image](https://user-images.githubusercontent.com/31688036/66210081-3b50cc80-e6b9-11e9-9a2e-38feba47a7aa.png)

I'm going to create a new issue because there should be something implemented that checks older `devon-ide` installations and overwrites those files. 

Now `mvn` gets installed correctly and I have no blocker issue so far. Again thanks for your support.
