### ISSUE TITLE
devon script in users home directory not properly overwritten on update

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/ide#269]
As a user, I want `devon-ide` to remove old ide related files when installing a new version so that I don't get any issue because of having old scripts on my home folder.

## Description

The basic problem is that I installed several months ago the  `devon-ide`. It created some files on the `.devon` home folder:

![image](https://user-images.githubusercontent.com/31688036/66210389-fe390a00-e6b9-11e9-8190-d7b676d293ad.png)

When I was testing the latest version ([Beta22](https://repo.maven.apache.org/maven2/com/devonfw/tools/ide/devon-ide-scripts/3.0.0-beta22/)) I faced this issue #268 because of these old files. The `devon-ide` did not remove/overwrite those files.

In my opinion, it should be implemented a way to install cleanly new versions.

**Comment by markusschuh** [comment]
Thank you, that you have verified this and opened this issue. I wasn't yet fully sure on this. For a first fix implementation, it might be o.k., if the setup just outputs an error message and stops execution, in case it detects existing components in user's home directory, which are outdated.

Meanwhile there was also some update logic realized, which allows the scriptlet update also in home directory from the already existing devon-ide instance. That would be probably the cleanest way. But this can't work, if the already installed version is older than the update feature was introduced.

Also it might be good, to have a manual fallback, since there are just too many variations of installation option on user's systems - so even a setup logic which can predict a lot of variants will run into a too complex to handle setup issue earlier or later.

**Comment by hohwille** [comment]
I have updated the title to be conform with what you are reporting as bug.
If I have understood correcntly you are saying that you have "updated" to a newever version of `devon-ide` but your old `devon` and `home` files in `~/.devon/` have not been updated accordingly.
This is indeed unexpected and we need further investigation why this has happened.
Can you clarify:
* Did you just install a new version of `devon-ide` to a new location and run `setup`?
* Or did you use `devon ide update scripts` command?
* I assume you are testing on windows, correct?

So what you are expecting is actually implemented here:
https://github.com/devonfw/ide/blob/c9c23df89a1d9f1fbbd49b701337b161698ade02/scripts/src/main/resources/scripts/command/ide#L126

Also I have tested this in several scenarios so we need to figure out what went wrong in your case. Can you debug this update? Or did you just never execute `setup` just like in #265?

**Comment by hohwille** [comment]
I can confirm this issue after updating to beta23 on windows. I still do not understand the root cause of this but indeed there is a bug with this update mechanism.

**Comment by hohwille** [comment]
Actually the error seems to come from old versions of `devon-ide` and their `devon` script. Once you have a more recent version of `devon-ide` installed (e.g. beta22+) it seems to work. I was reproducing the problem but updating from a beta11 to beta23 what actually fails due to bugs that have been fixed long time ago...

**Comment by jdiazgon** [comment]
Hi Jörg,

>  can confirm this issue after updating to beta23 on windows

Exactly, I was using Windows. 

> Did you just install a new version of devon-ide to a new location and run setup?

Yes. 

> Or did you just never execute `setup` just like in #265

Actually, I executed `setup` as mentioned on the docs. Most probably I explained my self incorrectly. What I did is:

1. https://repo.maven.apache.org/maven2/com/devonfw/tools/ide/devon-ide-scripts/[download]
2. extracted to `C:\projects\my-project-name` or `/projects/my-project-name`
3. ran `setup` script
4. Then I ran `devon eclipse` which threw some errors as I did not installed first the JDK.

> Actually the error seems to come from old versions of devon-ide and their devon script

Then I think we can close the issue

**Comment by markusschuh** [comment]
Quoting from the man page of bash:

```
. filename [arguments]
source filename [arguments]
    Read and execute commands from filename in the current shell environment and
    return the exit status of the last command executed from filename. If 
    filename does not contain a slash, file names in PATH are used to find the
    directory containing filename.
```

Due to that I assume, that the line  `"%BASH%" -c 'source devon'` from `devon.bat` does not necessarily execute the file `devon` within the same directory, but instead the devon from the `$HOME/.devon' directory, which was put at front of PATH by the setup of the older version.

Maybe a `"%BASH%" -c 'source ./devon'` were better here - but I have not yet checked on my own.

**Comment by hohwille** [comment]
> ... Maybe a "%BASH%" -c 'source ./devon' were better here ...

@markusschuh as always you are a smart and very sharp observer. Excellent suggestion I will consider.

**Comment by hohwille** [comment]
What I can still reproduce is that when I update via
```
devon ide update scripts
```
and a new version is available, downloaded and "installed", then the `devon` scripts are not updated. IMHO the `ide` commandlet is missing this specific part to run a script update after the update installation has passed.

**Comment by hohwille** [comment]
Actually this is already done:
https://github.com/devonfw/ide/blob/c9c23df89a1d9f1fbbd49b701337b161698ade02/scripts/src/main/resources/scripts/command/ide#L13
and
https://github.com/devonfw/ide/blob/c9c23df89a1d9f1fbbd49b701337b161698ade02/scripts/src/main/resources/scripts/command/ide#L19

However, it is not working on windows as the actual update of the `scripts` folder needs deferred execution so this is happening too late:
https://github.com/devonfw/ide/blob/c9c23df89a1d9f1fbbd49b701337b161698ade02/scripts/src/main/resources/scripts/functions#L398

**Comment by hohwille** [comment]
It is kind of odd to move even more specific logic from the `ide` commandlet to `functions` but currently this seems to be the only solution.
Any better ideas?

**Comment by hohwille** [comment]
IMHO I missed to track this issue and it is already fixed since a longer while.
When you update the IDE (`devon ide update scripts`) then the latest `devon` script is installed into user home.
You can always verify this by comparing output of these two calls:
* `devon -v`
* `devon help`

The first one prints the version that is bumped into the `devon` script itself when the release was build and reflects the version that is found first on your path what should be the one from your home directory.
The second one prints the version from the `$DEVON_IDE_HOME/scripts/devon` script what is your concrete IDE installation.

Further the `devon` script has been stabilized and shall not really change in the future what makes this problem rather irrelevant in the future.

**Comment by markusschuh** [comment]
It happened now for my installation again, that 

```
"${USERPROFILE}/scripts/devon.bat" 
```

was **not** updated to the newer version while I had run `devon ide update all`. Besides this the upgrade to latest version has worked pretty well.
It could be, my former version  (3.0.0-beta25) was too old to also update the `devon.bat`. I will try to debug more closer on next update, if something might still be wrong.
