### ISSUE TITLE
Version Control for default Settings URL

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/ide#331]
As an ide user, I want to install a consistent ide including matching default settings in any case so that the ide runs out-of-the-box

This is in addition to issue #55.

Apparently, as of Rel.3.2.3, the setup procedure always clones the latest version of the default settings git repository https://github.com/devonfw/ide-settings. (See scripts/command/ide function doUpdateSettings).

==> The line settings git repo should have proper release labels and the doInstall call should install the correct version (hwatever is correct for ide release x.y.z)

If the settings are being maintained and are either unstable or the user uses an older version of the ide where the newest settings do not match the ide any more, the user will run into probems (that may be hard to track down to a new commit in the ide-settings.git).

As  @hohwille puts it in #55: "Having version control for settings is a recommended feature in any case."

**Comment by hohwille** [comment]
I am unsure if such a feature really makes sense.
Who would really maintain versions of his settings git repository?
Are you aware that the concept of devonfw-ide is that each project has its own settings git repo?
Even if you need such a feature for an edge-case, you can setup devon-ide, then manually switch settings git to some other branch and do `devon ide update`.
What is your idea about extending this feature?
I currently assume that this is just a missunderstanding and we can close this issue.
Otherwise please provide additional details...

**Comment by Jan-PeterRichterCG** [comment]
@hohwille : the "killer use case" for a proper version control on the settings repository would be the clean installation of an older version of the ide that is incompatible with the newest revision of the settings. This use case may - atmittedly - be very rare.
The other "killer use case" is to tag known-to-be-consistent (e.g. tested) versions of the settings. Benefit:  if someone commits an "improvement" to the settings that in fact breaks some functionality, then this is commit will be the default settings for all people unlucky to clone the repository before the bug has been fixed. Obviously, the tag must be applied not at the moment of commit but after testing.

**Comment by hohwille** [comment]
Since we have now officially released `devonfw-ide` we plan and hope to be able to offer downward compatibility. Therefore newer versions should not be `incompatible` with the settings of an older installation.
For `oasp4j-ide` there is even a migration feature but surely not expected to be perfect for every edge-case:
https://github.com/devonfw/ide/blob/master/documentation/migration-from-devonfw-3.0.0-or-lower.asciidoc

The second thing you describe can all be archived with git. You can create branches, you can create tags, etc. Even our documentation suggests this to test changes in larger teams before pushing to default branch (`master` or `develop` however you name it).

> So as long as it is "impossible" for a broken commit to be the newest version, there is no need for version control.

It is not clear what you are trying to say. Do you want to suggest that we should not use git for the settings?
We are all developers and we all know that something can be broken. So also the settings could be broken. When something is broken, it should be fixed asap.
So to come to an end here:
Feel free to discuss with us in our discussion channels.
Issues should be used for reporting bugs or requesting concrete features. Hence, I am closing this issue as it is IMHO neither of those.
