### ISSUE TITLE
Eclipse import to wrong workspace

### ISSUE THREAD

**Issue by kaustubh-gajare** [devonfw/ide#480]
### Expected behavior

As a User, I want to checkout and import my project to specific workspace so that it does not go to project specific workspace.

### Actual behavior
I configured project for different workspace viz. 'project1' (see below file contents for project configuration), and also it is checked out to this workspace. But it still got imported to 'main' workspace. 

```
path=project1
workingsets=project1
workspace=project1
git.url=https://server/gitlab/project1.git
git.branch=main
build.path=.
build.cmd=mvn -DskipTests=true -Darchetype.test.skip=true clean install
eclipse=import
active=true
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create project configuration as give above in `settings\projects` folder.
2. Run `setup` command
3. Share git url for above settings repository

### Affected version:
2020.08.001

* OS: Windows
* Browser: Chrome

**Comment by hohwille** [comment]
1. the config you provided does not contain newlines. Can you first confirm that you have proper newlines in your actual project config as otherwise the bug is on your end.
2. please never share project details in the public. Please edit your message and replace your `git.url` with something like `https://example.com/project.git`.
3. As you wrote that it did checkout the project properly I assume that the newlines are just some copy&paste issue and you actually found a bug that we need to fix.

**Comment by hohwille** [comment]
What did you get from this output:
https://github.com/devonfw/ide/blob/1bf3124e2194b4ad4d2d9be6bc9931d64c4db69d/scripts/src/main/resources/scripts/command/project#L69

It is quite obvious from the code that it should create the workspace folder (if not already present):
https://github.com/devonfw/ide/blob/1bf3124e2194b4ad4d2d9be6bc9931d64c4db69d/scripts/src/main/resources/scripts/command/project#L72

And then it will `cd` into that workspace:
https://github.com/devonfw/ide/blob/1bf3124e2194b4ad4d2d9be6bc9931d64c4db69d/scripts/src/main/resources/scripts/command/project#L73

As the eclipse import should then be triggered inside this workspace directory I currently do not understand why this should not work:
https://github.com/devonfw/ide/blob/1bf3124e2194b4ad4d2d9be6bc9931d64c4db69d/scripts/src/main/resources/scripts/command/project#L87

**Comment by kaustubh-gajare** [comment]
Hi @hohwille ,

Yes, New Lines are already present. This is copy & paste error.

Regards,
kaustubh

**Comment by kaustubh-gajare** [comment]
Hi @hohwille ,

Any updates here? Or you can point me to different approach for this?

Regards,
Kaustubh

**Comment by hohwille** [comment]
I can meanwhile reproduce and confirm the bug.
It seems that the workspace is from the project's `.properties` file is honored for cloning the project but not for the eclipse import:
```
Starting eclipse import for /Users/hohwille/projects/test2/workspaces/project1/project1 into workspace main at /Users/hohwille/projects/test2/workspaces/main
```

Here `main` should be `project1`. I used this config in `settings/projects/project1.properties`:
```
path=project1
workingsets=project1
workspace=project1
git.url=https://github.com/devonfw/sonar-devon4j-plugin.git
git.branch=master
build.path=.
build.cmd=mvn -DskipTests=true -Darchetype.test.skip=true clean install
eclipse=import
active=true
```

**Comment by hohwille** [comment]
So the `project_workspace_path` is properly determined:
https://github.com/devonfw/ide/blob/306881afd2d924e88d18b7950988e05a39ea96b4/scripts/src/main/resources/scripts/command/project#L71
Then the script creates and enters this directory:
https://github.com/devonfw/ide/blob/306881afd2d924e88d18b7950988e05a39ea96b4/scripts/src/main/resources/scripts/command/project#L73
After that the project is imported (if configured accordingly):
https://github.com/devonfw/ide/blob/306881afd2d924e88d18b7950988e05a39ea96b4/scripts/src/main/resources/scripts/command/project#L87

As it seems the `project` commandlet is doing all correctly. So IMHO the `eclipse` commandlet is buggy when doing the `import` and does not honor the workspace (maybe because the variable `WORKSPACE` was already set before to `main`).

**Comment by hohwille** [comment]
Indeed the `eclipse` commandlet uses the variables `WORKSPACE` and `WORKSPACE_PATH` and itself ignores the current path (PWD). Before the commandlet is called the `devon` script sets these variables from the current path. As in this case we are calling `eclipse` commandlet directly from `project` commandlet the variables are not changed and therefore the bug happens.
So a fix is simple: in `project` commandlet, we have to properly set these two variables. I will create a PR to fix this bug.

**Comment by hohwille** [comment]
Fix seems to work as expected:
```
Starting eclipse import for /Users/hohwille/projects/test2/workspaces/project1/project1 into workspace project1 at /Users/hohwille/projects/test2/workspaces/project1
```

Creating PR now.
