### ISSUE TITLE
Error during installation when npm is already installed

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw/ide#483]
### Expected behavior

As a developer, I want devonfw ide to setup correctly so that I can use it without issues

### Actual behavior

When setting up devonfw ide in a katacoda environment (e.g. https://katacoda.com/devonfw/scenarios/cobigen-cli), error messages are shown during the installation process and 'npm' cannot be installed. The installer show the message 'npm is already installed'.

### Steps to reproduce

1. Open a katacoda tutorial (e.g. https://katacoda.com/devonfw/scenarios/cobigen-cli)
2. Execute the following steps:
  - execute 'wget -c https://bit.ly/2BCkFa9 -O - | tar -xz'
  - execute 'bash setup'
  - enter 'https://github.com/GuentherJulian/katacoda-scenarios-ide-settings.git' as the settings url (for installing 'java, mvn, npm and ng)
  - accept the license agreements with 'yes'

### Comments/Hints:
Console log:
...
Do you accept these terms of use and all license agreements? (yes/no) yes

Downloading java-11.0.5_10-linux.tar.gz from https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.5_10.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   675  100   675    0     0   2500      0 --:--:-- --:--:-- --:--:--  2500
100  187M  100  187M    0     0  8721k      0  0:00:22  0:00:22 --:--:-- 7253k
Successfully extracted archive java-11.0.5_10-linux.tar.gz to updates/extracted
Successfully installed java
To be fully functional please rerun 'devon' command to update your PATH properly.
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

*** Setting up mvn ***
Starting installation of maven to /root/devonfw/software/maven from https://archive.apache.org/dist/maven/maven-3//3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
Downloading maven-3.6.2.tar.gz from https://archive.apache.org/dist/maven/maven-3//3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8928k  100 8928k    0     0  18.0M      0 --:--:-- --:--:-- --:--:-- 18.0M
Successfully extracted archive maven-3.6.2.tar.gz to updates/extracted
Successfully installed maven
To be fully functional please rerun 'devon' command to update your PATH properly.
Successfully created /root/devonfw/conf/.m2/settings-security.xml
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T15:06:16Z)
Maven home: /root/devonfw/software/maven
Java version: 11.0.5, vendor: AdoptOpenJDK, runtime: /root/devonfw/software/java
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-111-generic", arch: "amd64", family: "unix"

*** Setting up npm ***
npm is already installed at /usr/bin/npm

*** Setting up ng ***
/root/devonfw/scripts/command/../functions: line 73: /root/devonfw/software/node/bin/npm: No such file or directory
Failed to run command: '/root/devonfw/software/node/bin/npm' install -g @angular/cli@latest --unsafe

******** ATTENTION ********
ERROR: Failed to install angular-cli ('/root/devonfw/software/node/bin/npm')
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 127
ERROR: command 'ng setup' failed with exit code 127

### Affected version:

* Linux (Ubuntu 18.04.4 LTS)
* Browser: -

**Comment by hohwille** [comment]
@GuentherJulian thanks for filing this issue and your helpful error description.
Indeed you found a bug that we seemed to miss out in our current tests.
If I am not mistaken the bug is here and in the following lines:
https://github.com/devonfw/ide/blob/1bf3124e2194b4ad4d2d9be6bc9931d64c4db69d/scripts/src/main/resources/scripts/command/ng#L16

I see the following options to fix this:
1. at the linked code-place we can first check if `npm` is available in the path and get its installation (`which npm`)
2. generally expect that `npm` is on the path and invoke it relatively (`npm`) instead of absolutely (`${DEVON_IDE_HOME}/software/node/npm`).
3. always install `npm` explicitly and use it from the current `devonfw-ide` installation

I would actually propose option 3. as we always follow the sandbox principle and want to be in control of the version and config of our tools whereas with a global installation we end up with all the problems and errors we had earlier and avoid with `devonfw-ide` already for all other tools.

**Comment by hohwille** [comment]
For option 3. we need to fix here:
https://github.com/devonfw/ide/blob/1bf3124e2194b4ad4d2d9be6bc9931d64c4db69d/scripts/src/main/resources/scripts/command/npm#L8
