### ISSUE TITLE
Failing settings creation path when starting the setup process.

### ISSUE THREAD

**Issue by cgrausal** [devonfw/ide#511]
### Expected behavior

As a developer, I want to install current last version https://repo.maven.apache.org/maven2/com/devonfw/tools/ide/devonfw-ide-scripts/2020.12.001/devonfw-ide-scripts-2020.12.001.tar.gz just extracting files on path and pressing setup.bat clicking on windows or executing setup from git bash.

### Actual behavior

Installation process fails when after using setup.bat from cmd or setup from git bash, settings folders is created on 
Working on path **C:\c\projects\settings** instead on **C:\projects.** 

### Affected version: 2020.12.001

* OS: Windows 10 Pro

PS: I tried also after turning off feature WSL (Windows Subsystem Linux).

**Comment by cgrausal** [comment]
![image](https://user-images.githubusercontent.com/39998272/104449658-3c9cc480-559f-11eb-8036-a0c763326f24.png)

**Comment by cgrausal** [comment]
![Uploading image.png…]()

**Comment by ssarmokadam** [comment]
@cgrausal  I am not able to reproduce this issue... As you can see in below images I have created folder testide and extracted content of tar file to it and run setup.bat file ... so ide is getting installed in testide folder which is expected behaviour.

![image](https://user-images.githubusercontent.com/16591200/104479533-8f02d300-55e9-11eb-98a5-40ee98ed89ab.png)


![image](https://user-images.githubusercontent.com/16591200/104479456-75618b80-55e9-11eb-8234-330c3a70cfc9.png)

**Comment by hohwille** [comment]
@ssarmokadam do you have WSL on your windows machine? If not could you install it and retest if that could cause the bug?

Otherwise I am also clueless. We would need a full trace-log from @cgrausal to understand better why this is happening. I still assume this is a special case that only happens for a few users.

What is interesting is that even in the logs from @ssarmokadam the path logged is `/c/...` and it seems to be mapped to `C:\...`. I am clueless why this works for most users but not for @cgrausal

**Comment by hohwille** [comment]
Could you both @ssarmokadam and @cgrausal report your versions of git-for-windows? Maybe a new version of git is causing this issue (for @cgrausal the log said `Cloning into /c/Devonfw/settings` and for @ssarmokadam it said `Cloning into C:/testide/settings). That looks like an interesting difference that could lead to the root problem. If we have traced the problem down, I can understand and then fix it. I guess we might need some path remapping like with cygpath and the other related things. See also #488

**Comment by ssarmokadam** [comment]
@hohwille I will restest it with WSL and contact carlos once again for trace logs

**Comment by hohwille** [comment]
I have received and analyzed a full trace-log. What I can see is that the entire setup looks normal and as planned. The circumstance that the `settings` are cloned to the wrong place on the disc are caused by `git` for windows itself when passing the path from a bash on windows.
Therefore I suggest the following test:
1. open a (git) bash on windows
2. `mkdir test`
3. `git clone --recursive https://github.com/devonfw/ide-settings.git ${PWD}/test

My assumption is that on @ssarmokadam's laptop (and for most other users) step 3. will clone the repo to the previously created `test` folder. However, on @cgrausal's machine this will create the folder structure below `C:\c\`.
If that is the case and my assumption is correct, the bug has been isolated from `devonfw-ide` and is a regression bug of `git` for windows. As I already suggested, please both provide your versions of `git` so we can compare. It is likely that if @ssarmokadam will upgrade/downgrade to the same `git` version as @cgrausal she can also reproduce the bug. As a workaround we could check for windows and then map the `bash` path to a windows path or simply cd to the directory where to clone and omit passing it as argument. After the clone do `cd -`.

**Comment by hohwille** [comment]
@cgrausal I have created PR #524 to fix this.
Could you apply the change locally to your IDE and test if that would fix your problem:
https://github.com/devonfw/ide/pull/524/files

**Comment by hohwille** [comment]
I have tested this on windows with the following git versions without getting this error:
* `2.29.2.windows.1`
* `2.30.0.windows.2`

So I assume that @cgrausal you have either a very old version of git or not an official git for windows at all (installed manually git via cygwin or something like this).

**Comment by hohwille** [comment]
I added the waiting-for-feedback label and hope to receive some feedback soon.
If the PR is tested and helps, we can include it in the release planned for this week.
Otherwise I will postpone this to an upcoming release. It seems it only happens in a rather exotic situation and therefore the priority is not high...

**Comment by cgrausal** [comment]
Hi, I upgraded the version to git version 2.30.0.windows.2 from official git plave and got the error. I changed the function script with modifications from https://github.com/devonfw/ide/pull/524/files. c:/c folder was not created but process ends up fast and without software installation.

**Comment by hohwille** [comment]
@cgrausal thanks for testing and feedback.
So we can conclude that the `git` version or installation does not seem to be causing this bug.
Still it is entirely unclear what setting or circumstance on your machine is causing this strange bug that does not seem to be reproducible by anyone else.

For my PR I now tested and noticed that I was too quick and it can not work as planned:
In order to avoid passing the (absolute) directory to the clone command ending up with this `C:\c` folder on your end, I thought that I first go into the directory and then clone the git repo there.
This can not work for two reasons: The target directory does not exist as the `git clone` command actually creates it.
Even if I create it before going into it, the `git clone` command creates another subdirectory if no argument for the path is provided. So I have to rework on that but I assume I can easily do this.

**Comment by hohwille** [comment]
OK, I have updated my PR #524 and have tested it.
As I am quite sure now that it is working I will include it into the release I will create today.
If we are lucky, this will workaround your bug and fix it.
In the worst case not but also nothing should break for anybody else.

**Comment by hohwille** [comment]
Merging PR #524 also closed this connected issue.
I will complete the changelog and hope this issue is really fixed.
Otherwise simply reopen and comment with your new observations.
@cgrausal If it really works for you with the new release comming out today I would also be very pleased, if you could leave us a comment confirming this.
