### ISSUE TITLE
Support external parent poms on devon java migrate

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#512]
As an architect, I want to upgrade my complex devonfw projects setup with a shared parent pom so that do not need to combine and extract the parent pom contents again and again for each migration.

I have a project setup with three git repos, two applications and one repo for shared modules including a shared parent module.
The shared parent module is parent of all three repository multi-module maven projects.

If I want to upgrade all applications to the next devonfw version I always need to reintegrate my shared parent-pom into the parent poms of the application repos and then run the automated migration. Afterwards, I need to revert the integration and extract the contents again into the shared parent-pom.

Just thinking out loud: possibly, it might be interesting to support <systemPath>${basedir}/../shared/shared-parent/pom.xml</systemPath> to be set temporarily in my projects depending on where the shared-parent pom is located on my system. With that, we could think of supporting systemPath lookup to automatically run the migration even across a multi-module project and allow migration in place. WDYT?

**Comment by maybeec** [comment]
oh sry, i should have tried it with relativePath, but not sure, whether this will make a difference. Is there support for pom with relativePath? no sure, why I tried with systemPath....

**Comment by hohwille** [comment]
@maybeec thanks for your feedback and suggestion for feature improvement.
IMHO when the versions (`devon4j`, etc.) are not in the pom the migration is invoked on but e.g. in a pom that comes from maven repo I have no clue how `devon migrate` could actually change it since it cannot access the pom.
Our  `devon migrate` is desigend to work on any project-structure compatible to what was created by our `archetype`.

What I do in such cases in order to still being able to use the migration:
* temporary add `devon4j.version` variable to your parent pom manually with the correct current `devon4j.version`
* run the migration
* manually move the `devon4j.version` to the external parent POM.

However, I am happy to improve here. We could:
* support projects that added an additional parent POM on top of the archetype
* if we can not determine `devon4j.version` we could check deps and structure if it still looks like a `devon4j` project and then prompt for the version.
* extend documentation of this feature with tipps as stated above
* in case of an error link to the documentation

PRs are always welcome ;)

**Comment by maybeec** [comment]
You are totally right, that we cannot access poms, which are not recoverable by the file system. But possibly we can read the relativePath property, which can be temporarily added by the architect on upgrade and otherwise, simply fail on upgrade like we do today with a hint (in case a parent exists) to include make the parent pom writable and reference it by <relativePath>.

Just moving the devon4j.version property solves to overcome the exception thrown at the moment, but it will not solve any automated upgrade which should have done some more changes even on the externalized parent pom code.

Possibly, I will have a look at it at some free time, but I think in general this would be quite valuable already if you try to externalize some shared libraries, which should anyhow take the same benefits of the parent poms declaration of devonfw.

**Comment by hohwille** [comment]
So we are talking about `devon migrate` being always invoked on the parent project of the modules `api`, `core` and `server`. The extension would apply if that parent itself does not contain the expected properties such as `devon4j.version`, etc.
After the change if `devon migrate` does not find the expected property to change, it would got to the parent pom (`relativePath` defaults to `../pom.xml`) and if present it would retry on that POM (recursively). This would allow to add parent POM(s) on top of the archetype and extract/move variables to that parent POM.

**Comment by maybeec** [comment]
> Do we agree that this is what we are planning?

yes. That would allow project setups like
```
workspaces/main/
  |- commons/
    |- pom.xml
  |- app1/
    |- api/
    |- core/
    |- server/
    |- pom.xml
```

whereas `app1/pom.xml` is referring it's parent pom with `relativePath` to `../commons/pom.xml`

**Comment by hohwille** [comment]
Is this still relevant?
I would tend to close this as wontfix.
I still see endless lists of issues that I am unable to cope with and very little contributors.

**Comment by maybeec** [comment]
At least we have projects running needing this. So far, we are running manual steps to restore the original state, do the migration and restore our design again.

**Comment by hohwille** [comment]
As devonfw has a new "focus" and we are getting rid of modules, etc. I will close this issue.
Still anybody is invited to provide a PR but I do not really see the need for this anymore.
