### ISSUE TITLE
Docker desktop alternative

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/ide#634]
As a project that has no license for docker desktop, I want to have an alternative docker variant as part of devon-ide so that I can still use devon-ide to set up docker.

Tasks:
- Evaluate existing alternatives (#689)
  - Docker in wsl
  - Lazydocker in wsl
  - Rancher desktop
- Add best alternative to devon-ide (#690)

**Comment by markusschuh** [comment]
The list above does not yet list real alternatives, since Lazydocker and Rancher can't provide the containerization layer on their own. But e.g. lazydocker can be installed on top of docker-ce to get the ascii ui.

Using docker-ce in WSL2 on Windows 21H2 works good  See https://dev.to/bowmanjd/install-docker-on-windows-wsl-without-docker-desktop-34m9 for the manual installation steps.

It may be possible to automate the setup to be run by devonfw-ide. Nevertheless the full setup needs changes both on the Windows host as well as within the WSL2 guest. This looks like quite some challenge for a bash script, that might run e,.g. per default in the bash emulation of git in windows. But nothing is impossible.

**Comment by maybeec** [comment]
Might be also interesting to check https://github.com/devonfw-forge/podman-minikube which is utilized and tested already in Spain.

**Comment by Bene90** [comment]
Evaluation topic. 
Suitable space regarding documentation?

**Comment by Bene90** [comment]
Last AC "Add best alternative to devon-ide" should be part of #690 right?
