### ISSUE TITLE
Evaluate SDKMAN

### ISSUE THREAD

**Issue by tobka777** [devonfw/ide#772]
As a developer, I want to evaluate SDKMAN so that I can find out how their solution works and if integration is possible.

Analysis and evaluation of the SDKMAN tool if we can use it inside devonfw-ide under the hood and gain some simplification or benefits. Maybe we can adopt version handling or integrate the tool.
The advantage of using SDKMAN could be that we could use the tool to install a tool and not have to write an integration for each tool. It must be noted how it behaves with different versions and installations.

https://sdkman.io/
https://github.com/sdkman/sdkman-cli

Acceptance criteria:
- [ ] Install and test SDKMAN
- [ ] Identify weaknesses and strengths
- [ ] What could we use in devon-ide?
- [ ] allows multiple clients (sandbox)
- [x] different version can be downloaded

Proposal by @baumeister25 in #635

**Comment by hohwille** [comment]
A first barrier is that SDKMAN requires `zip` to be present. In order to install it on windows they suggest to use `winget` but as `winget` itself is still beta the installation process of that is already too complex for most beginners and therefore is a problem for some of our targeted users.
However, I found this source of GNU Zip for Windows:
https://deac-fra.dl.sourceforge.net/project/gnuwin32/zip/3.0/zip-3.0-setup.exe

After installation zip was not on the path and SKDMAN installation still failed, but adding `C:\Program Files (x86)\GnuWin32\bin` to my `PATH` env variable solved this. After restarting Windows-Terminal I could then install SDKMAN.

Now, when I install some software with SDKMAN, I notice that SDKMAN by default works in a global way:
Everything is installed in users home directory under `.sdkman` folder. This does not fit to the sandbox and multi-tenancy approach of devonfw-ide. It might be possible to override the location of the `.sdkman` folder to one inside `$DEVON_IDE_HOME` on the commandline when calling  `sdk` command in devonfw-ide.
If we find a way to do this we can proceed further.
However, the following additional aspects need to be considered:
* Currently we install software to the `software` folder in `$DEVON_IDE_HOME` - using SDKMAN under the hood would change this structure significantly and we do not know what kind of custom scripts our users build on top of `devonfw-ide` that could then fail after an update that switches to SDKMAN
* While SDKMAN comes with an impressive list of tools that are already supported for download and installation. However, several tools we support are not supported by SDKMAN. We could consider supporting and contributing to SDKMAN to get these tools integrated as well:
```
Stop! jasypt is not a valid candidate.
Stop! jenkins is not a valid candidate.
Stop! sonarquube is not a valid candidate.
```
* SDKMAN uses its own versioning. So currently in `devonfw-ide` you configure `JAVA_VERSION=11.0.13_8` whereas in SDKMAN you would have to do `sdk install java 11.0.15-tem` and even though `Temurin` supports many versions those are not available in SDKMAN so if you need something specific like `11.0.13_8` you can not get it with SDKMAN. This could be a severe problem for our users as with SDKMAN we would add another layer inside can prevent us to get things solved we need for our projects.
* We have some rather specific features like adding EXTRA_JAVA_VERSION to setup two different versions of Java in parallel and to launch IDEs like Eclipse with a different version than the one that us used by default and by build tools like `maven` or `gradle`. However, it seems this could also be solved with SDKMAN that can install multiple versions of the same tool and set one of them as default. What appears a bit odd to me is that SDKMAN seems to create the default by *copying* the explicit versioned tool folder to a folder `current` what is wasting a lot of space on the disc. Symlinks in windows might be still too tricky to use smooth so that might be a pragmatic approach.
* We have crafted special advanced features for `devonfw-ide` like https://github.com/devonfw/ide/blob/master/documentation/software.asciidoc#custom and https://github.com/devonfw/ide/blob/master/documentation/software.asciidoc#shared and those are not supported by SDKMAN. If we would switch to use SDKMAN entirely to install software those features would be lost and projects using that features could not upgrade to such version. The question might still be how to integrate SDKMAN into `devonfw-ide`...

So as we can already see it does not seem to be as easy as one might thing from an outside perspective to simply replace our internal download and setup functions and replace them with SDKMAN.
However, I do not want to give up on this task and also want to highlight the benefits of SDKMAN:
* SDKMAN already supports a huge variety of existing tools and many of them are not yet supported by `devonfw-ide`.
* SDKMAN has a feature `sdk list «tool»` so e.g. `sdk list java` gives you the entire list of versions of Java that are supported and to choose from for installation. This is a very nice feature and `devonfw-ide` lacks of such features.
* SDKMAN seems to be crafted well. I digged a little in their bash code and you quickly notice that this was designed by professionals and not by bash hackers.

To compare SDKMAN and devonfw-ide:
While both tools can download various tools is an OS agnostic and simple way without messing your global OS, they are still very different:
* SDKMAN focuses on installation of tools only. It makes every user the expert to choose which version of what tool to install and use. It lets you alone with the configuration of the tool and also with integrations between tools. It is not designed for someone who is a newbe and just wants to start developing without knowing the exact requirements.
* `devonfw-ide` focuses on supporting development projects during their entire lifecycle. It aims to support that every developer on the team of that project has the same setup with the same tools, versions and configurations. One expert is sufficient to manage the configuration for an entire project while the rest of the team can simply run the setup with a single command without further need to think and choose. However, every team member still has the freedom to customize, improve and tweak if he is some kind of expert as well.

So roughly there could be the following options for integration of SDKMAN into devonfw-ide:
* We reverse-engineer SDKMAN and try to bring only the capabilities to download and extract tools into a given folder replacing our internal `doInstall` and `doDownload` functions of `devonfw-ide`
* We use SDKMAN as IS inside and under the hood of `devonfw-ide`. That is SDKMAN is either a per-requisite to `devonfw-ide` or `devonfw-ide` would automatically install SDKMAN for you. Here we still have different options:
  * Use SDKMAN only to get the software on your machine and from there bring them into `devonfw-ide` some other way e.g. by copying/moving/symlinking to our `software` folder.
  * Use SDKMAN in a way that it creates the installation into `$DEVON_IDE_HOME` instead of `~/.sdkman`.
  * Keep existing functionality and full compatibility but additionally integrate SDKMAN for new tools and stepwise see which features of `devonfw-ide` can be replaced with existing SDKMAN features without breaking any compatibility.

**Comment by hohwille** [comment]
So regarding the reverse-engineering:
```
sdk list java
```
does mainly nothing else then outputting this from `curl`:
https://api.sdkman.io/2/candidates/java/msys_nt-10.0-19043/versions/list?current=&installed=17.0.3-tem

And for download/installation it is also as simple:
```
sdk install java 18.0.1-tem
```

Simply triggers this `curl` download: https://api.sdkman.io/2/broker/download/java/18.0.1-tem/msys_nt-10.0-19043

So what they did is what we once also discussed for `devonfw-ide`:
They build a service on the web that acts as proxy to download any kind of tool.
We decided against this approach for `devonfw-ide` because we feared that such service could become the bottleneck and single-point of failure as if we can not guarantee 7/24 availability of that service the entire approach falls into pieces and users get blocked and therefore projects cannot proceed and deliver.

Another thing that gives me a real shiver in 2022.
SDKMAN downloads pre- and post-installtion hooks from this service:
https://api.sdkman.io/2/hooks/post/java/18.0.1-tem/msys_nt-10.0-19043
It does "remote code execution" by design.
So if the server gets hacked and an evil attacker changes this to a command deleting your entire disk, SDKMAN will delete your entire disk and users might not like this.
In devonfw-ide we always decided against such approaches due to IT-security.

**Comment by hohwille** [comment]
Finally, after testing SDKMAN more intensive I found many bugs in it.
So if someone still has any idea how devonfw-ide can further benefit from SDKMAN please let me know.
I will close this issue now as I do not see any further value in investing further into this issue.
