### ISSUE TITLE
Pip integration for python

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#840]
As discussed in #839 we need to create a commandlet to install and use `pip`.

For acceptance criteria as always see our [DoD](https://github.com/devonfw/ide/blob/master/documentation/DoD.asciidoc).

**Comment by alfeilex** [comment]
I have found to solutions to be able to deposit the installation of Azure CLI and other packages in the software directory. 

First solution: 
- Install package with `pip --target <directory_path> <package_name>`
- create a .pth file in software/python/Lib/site-packages and paste the previous path there
- add `${DEVON_IDE_HOME}/software/<directory_path>/bin` into `$PATH`

=> Leads to an error:
`Error loading command module 'rdbms': No module named 'pywintypes'`
even though the dll is available in the directory. (`<directory_path>/pywin32_system32/pywintypes310.dll`)

This is probably due to a still faulty dependency. But the script will be executed anyway (e.g `devon az`).

Second solution:
- install [virtualenv](https://virtualenv.pypa.io/en/latest/) with `pip install virtualenv`
- add `${DEVON_IDE_HOME}/software/python/Scripts` into `$PATH`
- navigate to the software and create virtual environment with `virtualenv <directory_name>` (copying python interpreter)
- run `activate.ps1` in `<directory_name>/Scripts` (add copied python **with pip** to $PATH)
- add `${DEVON_IDE_HOME}/software/<directory_path>/Scripts` into `$PATH`
- run pip install <package_name>

Runs perfectly without any problems. The created folder can be easily deleted.

Disadvantage: The structure with `bin` folder is not respected.

**Comment by Akuhana** [comment]
Preliminary pull request for pip commandlet implementation.
- Use `devon pip` to install pip.
- Use `devon pip install <package>` to install pip packages.
- Use `devon pip remove` to remove pip.
- Use `devon pip remove <package>` to remove a pip package.
