### ISSUE TITLE
scripts folder not added to PATH if setup.bat called from powershell

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#866]
@magail reported to me (I saw this in screensharing session) that after calling `setup.bat` and opening new `CMD` he still got:
```
devon is not recognized as an internal or external command, operable program or batch file.
```

After some debugging and analysis we found that the path adoption only worked for the local shell but was not persisted to the registry:
https://github.com/devonfw/ide/blob/71c62a97bc93bff4b302dc93d9d6e01ecd210943/scripts/src/main/resources/scripts/devon.bat#L30

Further testing and debugging revealed that this error only happened because he was using PowerShell.
When running setup.bat directly or from CMD it worked.

The https://devonfw.com Website however has a download button with a tooltip suggesting to use powershell by providing a powershell specific command (what a regular user might not even understand and it totally fails if pasted into any other shell like CMD or git-bash). Further the user told me that is extremely nasty that this is inside a tooltip that disappears while trying to copy&paste the instructions.

## Affect version
2022.04.003

## Steps to reproduce

1. have no devonfw-ide on your machine or remove ~/scripts from your PATH and ~/scripts/devon.bat from your disk.
2. open PowerShell
3. follow instructions from https://devonfw.com Download Button tooltip to install devonfw-ide (`Invoke-WebRequest -OutFile devonfw-ide-scripts.tar.gz 'https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.devonfw.tools.ide&a=devonfw-ide-scripts&v=LATEST&p=tar.gz'; tar -xvzf .\devonfw-ide-scripts.tar.gz; .\setup.bat`).
4. Open a new CMD shell
5. run `devon` command
6. See error `devon is not recognized as an internal or external command, operable program or batch file.`.

**Comment by hohwille** [comment]
Acceptance-criteria:
* [ ] bug was locally reproduced
* [ ] bug has been analyzed and ideally we found a web-link explaining the reason that we can link
* [ ] setup.bat fails in powershell with error message guiding to not run in powershell and documentation link with further details
* [ ] devonfw.com website has been updated or issue to do so has been created in https://github.com/devonfw/devonfw-guide/issues

**Comment by Akuhana** [comment]
The issue of the bug as I observed is that some functions don't work properly when trying to run them in Powershell. For example the for loop which iterates the directory and searches for a certain file
https://github.com/devonfw/ide/blob/cbaabfff9916f2d4f0b17741cff13ba5e699a8bf/scripts/src/main/resources/scripts/devon.bat#L16
By getting false results from the p variable, the following if statement will never be true
https://github.com/devonfw/ide/blob/cbaabfff9916f2d4f0b17741cff13ba5e699a8bf/scripts/src/main/resources/scripts/devon.bat#L17
The Powershell requires a different kind of command to iterate a set of files, which is why the best thing to do is, to run the setup.py on cmd.exe. The best solution in that case is not to tell the user to open the cmd.exe themselves, but to open it in the code automatically if it was detected that the powershell is being used for the execution of the setup.py script. I have tested this approach and it works without any issues.

**Comment by Akuhana** [comment]
As long as I understood the issue #409 correctly, it should be solved with the same pull request.

**Comment by hohwille** [comment]
> The Powershell requires a different kind of command to iterate a set of files, which is why the best thing to do is, to run the setup.py on cmd.exe.

I was already confused by this in your PR and renamed the title. IMHO you are talking about `setup.bat` when you write `setup.py`.

**Comment by Akuhana** [comment]
I'm sorry for the confusion, I indeed meant to write `setup.bat` instead of `setup.py`

**Comment by hohwille** [comment]
> The Powershell requires a different kind of command to iterate a set of files, which is why the best thing to do is, to run the setup.py on cmd.exe. 

I always thought that if I run a `*.bat` file from PowerShell, that it would be executed from CMD and not PowerShell.
So now I understand that it runs in PowerShell that seems to have also support for CMD commands but actually those do not behave 100% exactly the same. Obviously this is a strange design decision from Microsoft (why after all building so much ugly legacy into PowerShell instead of just calling CMD for the legacy *.cmd and *.bat stuff and keep PowerShell for new stuff like *.ps1 or what you type into PowerShell directly?) but we have to work around it.
