### ISSUE TITLE
Further improvements for nightly integration-tests

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#868]
From review of PR #844:
A new file `functions` was added in test:
> maybe this file should have a different name (e.g. test-functions, ``)? Otherwise we might end up in confusions if someone talks about functions and it is unclear if he means the productive functions or the test functions. We also have a functions documentation and some places that just talk about `functions` what is currently a unique file and so it is clear what we are talking about.

Further we currently have tests for
* terraform
* vscode

But how about other tools and features?
* eclipse
* intellij
* node
* npm
* az
* ng
* python
* pip
* yarn
* oc
* graalvm
* helm
* dotnet
* cobigen
* ...

**Comment by alfeilex** [comment]
To add new commands for the integration test, you can create a new file named `integration-test-<command>` and follow this example. 

https://github.com/devonfw/ide/blob/6ddbbc26e7e51fd008118d7165014691ac8a495c/scripts/src/test/bash/integration-test-terraform#L1-L4

Windows users must be careful when pushing the new test-scripts. Because Windows does not have a permission system like Linux, the following command must be run beforehand, otherwise a permission denied error will occur in github action run.

`git update-index --chmod=+x <script-path>`
