### ISSUE TITLE
Stability issue of nightly tests

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#912]
As PO of devonfw-ide, I want automated integration tests so that we can deliver quality and get feedback if some PR merge breaks our product by causing a bug.
Therefore we have implemented #691 and related stories.
The problem now is that we have added all available commands and that takes too long.
Github gives a lot of resources for free to support open-source projects.
Obviously there are limits and Microsoft can not give every project unlimited computing time (otherwise people would also mine bitcoins with GHA, etc.).
As it turns out, our tests run slow and after 6:00 hours github simply cancels the action what seems fair.

Questions:
1. Why does it take more than 6:00 h to run our tests? Are also the resources (CPU/bandwith/...) throttled so hard? I did not notice this so far. Maybe there is a problem on our side or one special commandlet is taking too long and test should be removed.
2. Should we focus on the most important commandlets if we have limits?
3. Could we find a way to run selected commandlets (e.g. by day of the week) so every commandlet is covered but not all in the same nightly-build?
4. Can we improve our logging so we can see easier how long the test took per command and what the status is? My initial idea was already that we have a final summary with all the tests we have run including their status (OK/NOK, duration). If we get cancelled by github should we print out this summary after each test so we spam the log more but also can see intermediate status?

**Comment by ahmedagdmoun** [comment]
After a small analysis and investigation I came with the following results:
The GHA resources are limited. As stated in Github Documentation (https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration): "Job execution time - Each job in a workflow can run for up to 6 hours of execution time. If a job reaches this limit, the job is terminated and fails to complete." So the workflows were canceled because the execution time of some jobs took more than 6 hours.
1. Unfortunately, there are different reasons why the tests took 6 hours depending on the OS.
For Ubuntu and MacOS, some commands (different commands) failed to run and the question "Do you want to continue?" was prompted out and waited infinitely for an answer till the 6 hours were reached. So we just have to find a way to automate skipping this question every time it's prompted out.
![ubuntu-test-failure](https://user-images.githubusercontent.com/98025282/194036877-1799139b-c42e-401a-92af-6a48baece879.PNG)
![MacOS-test-failure](https://user-images.githubusercontent.com/98025282/194036922-b60292ac-3739-4279-a539-a3976eb9abed.PNG)
For Windows, There was a full thread dump while installing Rancher Desktop. As this was already expected, I would suggest to simply exclude Rancher from the tests.
![windows-test-failure](https://user-images.githubusercontent.com/98025282/194036954-13e8f337-7699-4bb5-bfa6-c3cd7b3c9249.PNG)

2. I think that's not necessary as no commandlet will take so much time that the 6 hours are reached. We only have to solve the problems or exclude the commandlets that cause problems. I already did some time measurements and the longest test run of the commandlets that didn't cause the cancellation was 8min.

3. that would be an option if we really find out that some commandlets-tests would run successfully but would also need a lot of time but as I said above I don't think that's the problem.

4. Yes, as I mentioned in 2, I already implemented logic to calculate the time consumed by every test and print it in the logs. I don't know what do you mean by the status but if it's just if the test was successful or not, that was already implemented. Printing out a summary at the end would be also easy.

**Comment by maybeec** [comment]
I would strongly recommend to run every install in a separate job using the dynamic matrix feature of github actions

https://github.com/devonfw-tutorials/tutorials/blob/main/.github/workflows/buildMain.yml#L24

**Comment by alfeilex** [comment]
> I would strongly recommend to run every install in a separate job using the dynamic matrix feature of github actions
> 
> https://github.com/devonfw-tutorials/tutorials/blob/main/.github/workflows/buildMain.yml#L24

That's great suggestion. I see some difficulties with parallel execution of some commands. Currently the installation of each command runs in the ide that is build in test-setup. Some commands depend on other command... so there might be a conflict if e.g. azure (depends on python) and python command itself are run in parallel. 

If we decide to use the dynamic matrix function, we should probably change our complete test structure.

**Comment by maybeec** [comment]
There are two questions here for me: 

1. The question for me is here, whether the devonfw IDE would automatically install python in case you install azure client.
If so, you can do both in parallel as every execution would run in a newly setup machine. 
2. If the dependencies are not automatically installed, do you really need the dependencies for testing proper installation? Or is the installation crashing otherwise? It's about the question of installation verification which might look a little different depending on the capabilities of devonfw ide. But both is possible

**Comment by hohwille** [comment]
@maybeec 1. applies.
According to waste (carbon footprint) there is nothing speaking against your suggestion to use dynamic matrix feature.

For the moment we have resolved the fundamental problems with PR #937.
Now some real bugs are revealed that we also fix.
Then we hope to see green nightly tests :)

To improve the stability the dynamic matrix feature is also promising to me.
