### ISSUE TITLE
Improve python download of available versions

### ISSUE THREAD

**Issue by sarahffm** [devonfw/ide#927]
As a devon IDE user, I want to be able to download specific python versions without errors.
Currently, a number of versions in the available-versions file for Python can't be downloaded with the download URL specified in https://github.com/devonfw/ide-mirrors/blob/master/python/urls.

For windows the download URL looks like this when the extension and os mappings are filled in:
https://www.python.org/ftp/python/${version}/python-${version}-embed-win32.zip
But the actual download links (from the same website) of some versions have a different format, for example:
https://www.python.org/ftp/python/3.9.14/Python-3.9.14.tgz (or other extensions but not .zip)

Examples of versions that don't work with the current URL:
3.11.0, 
3.9.14, 
3.8.11 - 3.8.14, 
3.7.2,
...

Version 3.11.0 might be a pre-release or something like that. If that's really the case, it should actually not be listed in the available-versions file.

Related Issue: 
#826

**Comment by alfeilex** [comment]
It seems that there are security bugfix releases (e.g. [3.9.14](https://www.python.org/downloads/release/python-3914/)) which don't provide embeddable zip files for windows to install. The installation on MacOS and Linux should work with all versions because the installation of Python there builds from source code with .tgz file and this format is provided by each version.

Maybe we can modify the python command to build Python from source on windows systems as well. But currently I have troubles to install python on Linux and probably on MacOS as well.

**Comment by alfeilex** [comment]
I have started a discussion [here](https://discuss.python.org/t/url-of-labeled-python-releases/20175) to get information about available release url's.

**Comment by alfeilex** [comment]
Here is the PR https://github.com/devonfw/ide-mirrors/pull/41 in case we need stable python versions after the next _doInstall_ merge.

**Comment by alfeilex** [comment]
#963 will fix this issue. Issue can be closed.

**Comment by alfeilex** [comment]
https://github.com/devonfw/ide/issues/963 will fix this issue. Issue can be closed.
