### ISSUE TITLE
Make mirrors stable for latest versions

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#963]
We want to merge PR #934 that is properly implemented.
However, this PR reveals that several `available-versions` files are incorrect and contain (latest) versions that can not be downloaded or installed. Details:
* #959
* #950
* #947
* potentially #946
* more errors, we do not have issues for all problems yet (see also comments of PR #934)

The pragmatic idea is to disable the workflow for `ide-mirrors` that automatically updates the `available-versions` files.
Then we can manually maintain these versions and remove invalid versions.
Potentially we can even add new versions manually from time to time.
However, we will focus our energy on issue #941 and want to keep this issue simple.
ACs:
* [x] DoD
* [x] `devon «tool» setup` should work for all available tools (with PR #934 being merged) and install the latest version from `available-versions` for our 3 major supported OS. If the latest version is broken, simply remove it from or correct it in `available-versions` manually.

**Comment by cinnamon-coder-hub** [comment]
Good idea :+1: 
Also I wanted to note, that while testing the setup of our commandlets on linux for PR #934, 
I also looked for alternatives in some cases that would make the download of new versions work again 
(see the comments in https://github.com/devonfw/ide/pull/934). Maybe this helps a little.

**Comment by alfeilex** [comment]
PR is ready for review: https://github.com/devonfw/ide-mirrors/pull/44

**Comment by cinnamon-coder-hub** [comment]
> Good idea +1 Also I wanted to note, that while testing the setup of our commandlets on linux for PR #934, I also looked for alternatives in some cases that would make the download of new versions work again (see the comments in #934). Maybe this helps a little.

To keep the remarks on the radar, while closing the PR #934, I'll add them here within this comment.

**az:** 

When trying to setup azure on linux mint the setup of python is needed.
It seems as if the python download url changed slightly, but significantly.
It turned out, that the version in the download-url isn't 3.12.0, as our script would expect, but 3.12.0a1.
Expected download-url: https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz .
Actual download-url: https://www.python.org/ftp/python/3.12.0/Python-3.12.0a1.tgz .
Therefore the download just fails. This is another argument for an manually editable list of versions I guess.


**eclipse:**

The devon-ide takes a version number of eclipse for which the stable version hasn't been released yet. 
For an example see [this discussion](https://github.com/devonfw/ide/pull/934/files#r1008016946).


**npm and ionic:**

The setup of ionic on linux fails, because the install directory of npm can't be determined. 
This can be fixed by modifying line 30 of
https://github.com/devonfw/ide/blob/11db4ef9862f5f7baa8b89e9f3c14d15bd0380dd/scripts/src/main/resources/scripts/command/ionic#L29-L33
as mentioned by @alfeilex  in the [discussion](https://github.com/devonfw/ide/pull/934/files#r1010543624). 
If the path for the npm_command variable is the same on linux and mac, then  `[ -x "${npm_command}" ]` or `[  !doIsWindows ]` could be used instead of `[ ! -x "${npm_command}" ]`. 

**VSCode**

It seems as if the download url of VS Code for Linux changed, so the installation doesn't work.
As new source for the download url https://code.visualstudio.com/sha could be an option.
For the most recent stable version of VSCode on debian-based linux the url currently looks like this:
https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64.

**Comment by alfeilex** [comment]
Can be closed: PR is here: https://github.com/devonfw/ide-mirrors/pull/44

**Comment by hohwille** [comment]
> It seems as if the python download url changed slightly, but significantly.
> It turned out, that the version in the download-url isn't 3.12.0, as our script would expect, but 3.12.0a1.
> Expected download-url: https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz .
> Actual download-url: https://www.python.org/ftp/python/3.12.0/Python-3.12.0a1.tgz .
> Therefore the download just fails. This is another argument for an manually editable list of versions I guess.

IMHO the download URL did not change. Again here we have detected a version `3.12.0` that is not yet officially released.
If you compare this with the previous version:
https://www.python.org/ftp/python/3.11.0/

You can see that in this `3.11.0` folder there is the official release as `Python-3.11.0.tgz` but there are also these `a1`-`a7`,`b1`-`b5`, and `rc1`-`rc2` versions. IMHO `a` is for `alpha`, `b` for `beta` and `rc` for `release candidate`. So all these versions are pre-releases that we should ignore. We have to wait until an official `3.12.0` release is available. @alfeilex had removed `3.12.0` already from available-versions. So there is nothing left to do here. We can re-add it once that version is officially available.

**Comment by hohwille** [comment]
> The devon-ide takes a version number of eclipse for which the stable version hasn't been released yet.
> For an example see [this discussion](https://github.com/devonfw/ide/pull/934/files#r1008016946).

This is also what @alfeilex had fixed. So also done.

**Comment by hohwille** [comment]
> It seems as if the download url of VS Code for Linux changed, so the installation doesn't work.
> As new source for the download url https://code.visualstudio.com/sha could be an option.
> For the most recent stable version of VSCode on debian-based linux the url currently looks like this:
> https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64.

Oh, cool. This is an excellent finding with this `sha` URL. We should first try if we can download all versions for all OS and architectures via this new URL scheme with some magic changes of mirrors and without breaking older releases of devonfw-ide already released and using our mirrors.

However, current URL Schema is:
https://update.code.visualstudio.com/${version}/${os}/stable
For linux we map `os` to `linux-x64`.
Latest available version is `1.73.0` resulting in:
https://update.code.visualstudio.com/1.73.0/linux-x64/stable
That download link is working perfectly for me. So what is the actual problem?

**Comment by cinnamon-coder-hub** [comment]
@hohwille  the problem was solved by @alfeilex as he removed the version "v14". Before that my download url generated by the devon-ide looked like this 
https://update.code.visualstudio.com/v14/linux-x64/stable.
So in general Alex made a good and fast PR, which fixed the above mentioned problems :+1:
